image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
- go
- hut
- ruby-full
- ruby-dev
environment:
site: 1kb.club
sources:
- https://git.sr.ht/~bt/1kb-club
tasks:
- install-bundler: |
    sudo gem install bundler
- build: |
    - if [ "$SRHT_BRANCH" = "deploy" ]; then
        cd 1kb-club
        sudo bundle install
        sudo bundle exec jekyll build
      fi
- package: |
    - if [ "$SRHT_BRANCH" = "deploy" ]; then
        cd 1kb-club/_site
        tar -cvz . > ../../site.tar.gz
      fi
- upload: |
    - if [ "$SRHT_BRANCH" = "deploy" ]; then
        hut pages publish -d 1kb.club site.tar.gz
      fi