image: debian/stable
packages:
- ruby-full
- ruby-dev
- rsync
sources:
- https://git.sr.ht/~bt/1kb-club
secrets:
- 07201d32-1451-4a8f-9bff-ce8b2232c67d
tasks:
- install-bundler: |
    sudo gem install bundler
- build: |
    cd 1kb-club
    sudo bundle install
    sudo bundle exec jekyll build
- deploy: |
    cd 1kb-club
    rsync --rsh="ssh -o StrictHostKeyChecking=no -i ~/.ssh/07201d32-1451-4a8f-9bff-ce8b2232c67d" -rzP _site/ bt@1kb.club:/var/www/1kb.club
